{"version":3,"sources":["error_boundaries/components/ErrorBoundary.jsx","error_boundaries/components/PanelWithError.jsx","error_boundaries/DemoErrorBoundaries.jsx"],"names":["ErrorBoundary","props","_this","Object","classCallCheck","this","possibleConstructorReturn","getPrototypeOf","call","state","hasError","error","info","setState","console","react_default","a","createElement","children","React","Component","PanelWithError","name","toLowerCase","DemoErrorBoundaries","id","ErrorBoundary_ErrorBoundary","PanelWithError_PanelWithError"],"mappings":"0JAEqBA,cACnB,SAAAA,EAAYC,GAAO,IAAAC,EAAA,OAAAC,OAAAC,EAAA,EAAAD,CAAAE,KAAAL,IACjBE,EAAAC,OAAAG,EAAA,EAAAH,CAAAE,KAAAF,OAAAI,EAAA,EAAAJ,CAAAH,GAAAQ,KAAAH,KAAMJ,KACDQ,MAAQ,CAAEC,UAAU,GAFRR,iFAKDS,EAAOC,GAEvBP,KAAKQ,SAAS,CAAEH,UAAU,IAE1BI,QAAQF,KAAK,OAAQD,EAAOC,oCAI5B,OAAIP,KAAKI,MAAMC,SAENK,EAAAC,EAAAC,cAAA,mCAEFZ,KAAKJ,MAAMiB,gBAlBqBC,IAAMC,WCA5BC,mLAEjB,OACEN,EAAAC,EAAAC,cAAA,oBAESZ,KAAKJ,MAAMqB,KAAKC,sBALaJ,IAAMC,qDCE7BI,cACnB,SAAAA,IAAc,IAAAtB,EAAA,OAAAC,OAAAC,EAAA,EAAAD,CAAAE,KAAAmB,IACZtB,EAAAC,OAAAG,EAAA,EAAAH,CAAAE,KAAAF,OAAAI,EAAA,EAAAJ,CAAAqB,GAAAhB,KAAAH,QACKI,MAAQ,CAAEgB,GAAI,GAFPvB,wEAKZ,OACEa,EAAAC,EAAAC,cAAA,WACEF,EAAAC,EAAAC,cAACS,EAAD,KACEX,EAAAC,EAAAC,cAACU,EAAmBtB,KAAKI,gBATcW","file":"static/js/4.af83dd50.chunk.js","sourcesContent":["import React from 'react';\n\nexport default class ErrorBoundary extends React.Component {\n  constructor(props) {\n    super(props);\n    this.state = { hasError: false };\n  }\n\n  componentDidCatch(error, info) {\n    // Display fallback UI\n    this.setState({ hasError: true });\n    // You can also log the error to an error reporting service\n    console.info('...>', error, info);\n  }\n\n  render() {\n    if (this.state.hasError) {\n      // You can render any custom fallback UI\n      return <h1>Something went wrong.</h1>;\n    }\n    return this.props.children;\n  }\n}","import React from 'react';\n\nexport default class PanelWithError extends React.Component {\n  render() {\n    return (\n      <div>\n        {/*This generates an exception since name is not defined */}\n        hello {this.props.name.toLowerCase()}\n      </div>\n    )\n  }\n}","import React, { Component } from 'react';\nimport ErrorBoundary from './components/ErrorBoundary';\nimport PanelWithError from './components/PanelWithError';\n\nexport default class DemoErrorBoundaries extends Component {\n  constructor() {\n    super();\n    this.state = { id: 1 }\n  }\n  render() {\n    return (\n      <div>\n        <ErrorBoundary>\n          <PanelWithError {...this.state}/>\n        </ErrorBoundary>\n      </div>\n    );\n  }\n}\n\n"],"sourceRoot":""}